### ISSUE TITLE
Instruction on workflow on jupyterhub? 

### ISSUE THREAD

**Issue by sarambl** [MetOs-UiO/eScience2024#10]
Maybe this is already in the pipeline, but maybe we should have an instruction on what to do once you are on the jupyter hub? 
Like 
1) Clone the projects folder (should they clone any of the others?) 
2) If you download data, put it here xx
3) Create your notebooks here xxx

**Comment by mvdebolskiy** [comment]
Well, you just assigned yourself to do that. 😅 Initiative is punishable.

**Comment by mvdebolskiy** [comment]
I'll start a pr in a couple of hours with some skeleton.

**Comment by sarambl** [comment]
haha, right, should have seen that coming! Ok, but I'll do it once the git stuff is ready (https://metos-uio.github.io/eScience2024/git_integration/) because I actually don't know how that'll work right now 😅 

But basically we want them to 
- [x] clone the repos they need (probably just the project one initially) in their home? 
- [x] If they want to download anything, can they just create a data folder in their home if it's smaller than some size? 
- [x] They put their notebooks in their assigned project folder e.g. (https://github.com/MetOs-UiO/eScience2024-projects/tree/main/Group1) 
- [x] They each create a branch?

**Comment by MichaelSchulzMETNO** [comment]
My idea is -  fork to your own private github, clone from there, and pull and push back between your private fork on github and your jupyterhub clone. And once this is fine, sync the fork and create a pull request to contribute to the github main from the course.

**Comment by MichaelSchulzMETNO** [comment]
And yes, use the group folder  ! Then there are less conflicts.

**Comment by mvdebolskiy** [comment]
I will add the instructions about the git tab on the sever and some CLI commands. If they work in separate folders, the PRs should go to `master` directly. Unless you want to collect all the changes in some other folder and push into master less frequently.

**Comment by sarambl** [comment]
I feel this issue has been adressed, no?
