### ISSUE TITLE
Identifying and adding old notebooks to new repo and adjusting to current environment

### ISSUE THREAD

**Issue by sarambl** [MetOs-UiO/eScience2024#23]
I'm starting now to go through the old notebooks and find what is most relevant still. I have now identified:
- [x] Masked and weighted avg: https://pangeo-data.github.io/escience-2022/examples/notebooks/masked_and_weighted_average.html
- [x] Is this one still the way to access ebas? https://pangeo-data.github.io/escience-2022/examples/notebooks/from_ebas_using_xarray.html
- [x] Using cartopy and projections: https://pangeo-data.github.io/escience-2022/examples/notebooks/projections.html
- [x] Is this still the way to access aeronet data? https://pangeo-data.github.io/escience-2022/examples/notebooks/read-AERONET.html
- [x] Regridding: https://pangeo-data.github.io/escience-2022/examples/notebooks/xesmf_regridding.html
- [x] I am also making one on hybrid sigma to pressure coordinates. 

@MichaelSchulzMETNO maybe you have some opinions on this?

**Comment by MichaelSchulzMETNO** [comment]
I think we just add what we remember useful. No harm in putting too much. We can maybe reorder after a while by importance.

**Comment by mvdebolskiy** [comment]
Can you add PR# for the tasks?

**Comment by sarambl** [comment]
I don't know how to do it or what exactly you mean by that.

**Comment by sarambl** [comment]
I think I managed? I'm such a pro now 🥳
