### ISSUE TITLE
Getting building error 

### ISSUE THREAD

**Issue by sarambl** [MetOs-UiO/eScience2024#41]
I get this error when I try to build with the branch add_examples. Any input @mvdebolskiy ?
```
Extension error:
Could not import extension sphinx.builders.linkcheck (exception: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' (/Users/sarablichner/anaconda3/envs/escience_docs/lib/python3.12/site-packages/charset_normalizer/constant.py))
```
<img width="1135" alt="image" src="https://github.com/MetOs-UiO/eScience2024/assets/17406708/ad26f021-3769-4fec-8ed0-bf0f4b83d9e4">

**Comment by mvdebolskiy** [comment]
Can you try to `pip install -r requirements.txt` again? Also, remove `_build ` and `jupyter_exectue` folders.

**Comment by sarambl** [comment]
Ok, tried that, no change!

**Comment by mvdebolskiy** [comment]
Did you do something to that conda environment you are using?

**Comment by sarambl** [comment]
I'm trying to re-install a clean env now. Let's see!

**Comment by sarambl** [comment]
Fixed it!! Thanks.
