### ISSUE TITLE
Enable discussions? 

### ISSUE THREAD

**Issue by sarambl** [MetOs-UiO/eScience2024#42]
@mvdebolskiy , can we enable discussions on this page? If we can, would it be better here, or on the projects folder? 

@theodorekhadir @juliaasp 

P.S. I could not, but I was thinking it might be because I am not the owner of the page.

**Comment by mvdebolskiy** [comment]
Done. Please add some text about it in the documentation. (hopefully with a screenshot).

**Comment by sarambl** [comment]
Excellent! Thanks! @theodorekhadir, @juliaasp , do you think you could add some instructions to this?

**Comment by mvdebolskiy** [comment]
Done for the projects repo. Disabled for the org and this repo.
