### ISSUE TITLE
Download CESM-PPE pre-industrial

### ISSUE THREAD

**Issue by Ovewh** [MetOs-UiO/eScience2024#47]
@sarambl Wan't to have the PI ppe runs in addition to the PD runs already on Nird.

https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2.cam6.ppe.pi_timeseries.atm.hist.monthly_ave.html

**Comment by mvdebolskiy** [comment]
@Ovewh downloading PI to `/datalake/NS9560K/CAM6_CESM_PPE/PI/all/PI_timeseries`. we can restructure that into the same way as PD with a bash script later. Or make catalogs for both.

**Comment by mvdebolskiy** [comment]
Will take 120 hours to get the full PI_timeseries.

**Comment by mvdebolskiy** [comment]
@Ovewh https://arc.ucar.edu/articles/650 LOL

**Comment by Ovewh** [comment]
@mvdebolskiy I have rebuilt the intake catalogs for the CESM-PPE could you copy it over?

fc-3auid-3a9fdc0c87-2d7836-2d4bdc-2db802-2d9a250c322e3b/catalogs/cesm-ppe.csv

**Comment by mvdebolskiy** [comment]
@Ovewh is the aggregation control in those updated?

**Comment by Ovewh** [comment]
> @Ovewh is the aggregation control in those updated?

Should only be the table.

**Comment by mvdebolskiy** [comment]
@Ovewh try it.

**Comment by sarambl** [comment]
How's it going??? :D

**Comment by mvdebolskiy** [comment]
@sarambl  1.4 Tb out of around 3.

**Comment by sarambl** [comment]
haha, great :party: And that's the monthly, right?

**Comment by mvdebolskiy** [comment]
> haha, great :party: And that's the monthly, right?

Yes. I am not sure the whole dataset is 3Tb. Just judging by the filelist.

**Comment by sarambl** [comment]
@Ovewh can you rebuild the catalog?

**Comment by Ovewh** [comment]
I have build the catalog at `/mnt/craas1-ns9989k-geo4992/dataporten-home/fc-3auid-3a9fdc0c87-2d7836-2d4bdc-2db802-2d9a250c322e3b/catalogs/cesm-pi-ppi.json`. It's a seperate catalog for the PI data, i'll merge them into one later.

**Comment by sarambl** [comment]
Thanks @Ovewh ! Can we update again? Also, can I read it the same way as the others?

**Comment by sarambl** [comment]
Also, I don't find that file somehow!

**Comment by sarambl** [comment]
@mvdebolskiy thanks a lot for the new file! It doesn't work though :P I think you need to remove the "file:" in the json file pointing to the csv file. It tries to read it like this:
```python
FileNotFoundError: [Errno 2] No such file or directory: '[/mnt/craas1-ns9989k-geo4992/data/catalogs/](https://escience2024.craas1.sigma2.no/mnt/craas1-ns9989k-geo4992/data/catalogs/)file:///mnt/craas1-ns9989k-geo4992/escience2024/data/catalogs/cesm-ppe-pi-sara.csv'
```

**Comment by mvdebolskiy** [comment]
> I have build the catalog at `/mnt/craas1-ns9989k-geo4992/dataporten-home/fc-3auid-3a9fdc0c87-2d7836-2d4bdc-2db802-2d9a250c322e3b/catalogs/cesm-pi-ppi.json`. It's a seperate catalog for the PI data, i'll merge them into one later.

I have made another one `/mnt/craas1-ns9989k-geo4992/data/catalogs/cesm-ppe-pi-sara.json` for the variables @sarambl  has selected. Will redo when I get the full data.

Btw, @Ovewh thx for making the `nirddmc` tool. Would you like to add it into the docs?

**Comment by mvdebolskiy** [comment]
> @mvdebolskiy thanks a lot for the new file! It doesn't work though :P I think you need to remove the "file:" in the json file pointing to the csv file. It tries to read it like this:
> 
> ```python
> FileNotFoundError: [Errno 2] No such file or directory: '[/mnt/craas1-ns9989k-geo4992/data/catalogs/](https://escience2024.craas1.sigma2.no/mnt/craas1-ns9989k-geo4992/data/catalogs/)file:///mnt/craas1-ns9989k-geo4992/escience2024/data/catalogs/cesm-ppe-pi-sara.csv'
> ```

Try again.

**Comment by sarambl** [comment]
🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉 🥳 🥳 🎉

**Comment by mvdebolskiy** [comment]
@sarambl check the `cesm-ppe-pi-mon.json`.

**Comment by sarambl** [comment]
Looking amazing!!

**Comment by mvdebolskiy** [comment]
@sarambl  do you still want the daily?

**Comment by sarambl** [comment]
Nope, think it's fine without

**Comment by mvdebolskiy** [comment]
@sarambl @juliaasp what are the links for the 2022 and 2021 s3 storage? I want to add it to the data description.
