### ISSUE TITLE
Data access description.

### ISSUE THREAD

**Issue by mvdebolskiy** [MetOs-UiO/eScience2024#5]
- [x] overall mounted data on nird 
 - [x] satellite data
 - [x] CMIP6 intake catalog nird @Ovewh

**Comment by mvdebolskiy** [comment]
@Ovewh  any luck on intake catalogs? I can increase the RAM quota on `vc-test` for building them If the builder is crushing. Since all the mounts on jupyterhub are the same within same project space, you can make catalogs there and we'll just move them into a shared folder in the production hub.

**Comment by Ovewh** [comment]
> @Ovewh any luck on intake catalogs? I can increase the RAM quota on `vc-test` for building them If the builder is crushing. Since all the mounts on jupyterhub are the same within same project space, you can make catalogs there and we'll just move them into a shared folder in the production hub.

The data is not mounted on ´vc-test´? Perhaps time to open the production server.

I'm working on a small [command-line tool](https://github.com/Ovewh/nirddmc) for building the catalogs using [ecgtools](https://ecgtools.readthedocs.io/en/latest/index.html). I'm working on adding functionality so CMIP6 catalogs from different sources e.g local and remote can be merge into one. It would be nice to have vc-test mounted so i can test it. Now I have only tested running it from the nird login node.

**Comment by mvdebolskiy** [comment]
Oh, right. the mounts can not be overwriten after the hub is created. Well, there are mounts for keyclim, cmip6 and other on the `escience2024-test`.

**Comment by Ovewh** [comment]
@mvdebolskiy I have built a catalog of local CMIP6 data. 
`fc-3auid-3a9fdc0c87-2d7836-2d4bdc-2db802-2d9a250c322e3b/cmip6.json` and `fc-3auid-3a9fdc0c87-2d7836-2d4bdc-2db802-2d9a250c322e3b/cmip6.csv`

**Comment by mvdebolskiy** [comment]
@Ovewh Is this all data that is suppose to be there? Also, for some reason ecg is writing a weird path into `.json` for the `.csv` file. I had to go  and change it manually after I've moved it to `/mnt/craas1-ns9989k-geo4992/data/` you can see it there.
![image](https://github.com/MetOs-UiO/eScience2024/assets/80036033/7bc59528-bd14-4cd3-9528-37f013081eaf)

**Comment by Ovewh** [comment]
> @Ovewh Is this all data that is suppose to be there? 

It supposed to be except the NorESM data. I'll make a seperate catalog for that. Also there are some data that was not in the standard ESGF format which was not picked up. 
 
> Also, for some reason ecg is writing a weird path into .json for the .csv file. I had to go and change it manually after I've moved it to /mnt/craas1-ns9989k-geo4992/data/ you can see it there.

Looks correct to me. But I have to give a directory for where to store the catalog and i set it to be my home so i believe perhaps that was the issue

**Comment by Ovewh** [comment]
I was also thinking about merging the pangeo remote data and local into one catalog. So that we can accesses what is not available locally from pangeo.

**Comment by mvdebolskiy** [comment]
Oh. Ok. I can always change jsons before putting them into the shared data folder. Can you test the one in the `mnt/craas1-ns9989k-geo4992/data` if datasets are accessable not just catalogs?

**Comment by Ovewh** [comment]
Works fine I tested the cmip.json catalog.

**Comment by Ovewh** [comment]
I made an updated catalog merging all of noresm + pangeo + local. here: `merged-cmip6.json`, `merged-cmip6.csv` under `home/fc-3auid-3a9fdc0c87-2d7836-2d4bdc-2db802-2d9a250c322e3b`. When combining everything the it becomes quite large, so idk what is best?

**Comment by mvdebolskiy** [comment]
> I made an updated catalog merging all of noresm + pangeo + local. here: `merged-cmip6.json`, `merged-cmip6.csv` under `home/fc-3auid-3a9fdc0c87-2d7836-2d4bdc-2db802-2d9a250c322e3b`. When combining everything the it becomes quite large, so idk what is best?

I've tried cmip6.json and it just takes forever to load things into dataset dictionary without doing catalog.search() first. I think we should just make a HUGE warning in the documentation to not to load everything at once. 

Or we can try splitting the combined one by `institution_id`.

**Comment by Ovewh** [comment]
> I've tried cmip6.json and it just takes forever to load things into dataset dictionary without doing catalog.search() first. I think we should just make a HUGE warning in the documentation to not to load everything at once.

Of course that would be dumb. Always best to query the catalog so that it only contain what you need. It is a good idea to demonstrate the workflow and how to use the catalog. I can also include how to store cutout in their local directory of the whole catalog containing only the experiments they would be interested inn.   


> Or we can try splitting the combined one by `institution_id`.

If we were to split it makes most sense to me to split according to `activity_id`.

**Comment by mvdebolskiy** [comment]
> > I've tried cmip6.json and it just takes forever to load things into dataset dictionary without doing catalog.search() first. I think we should just make a HUGE warning in the documentation to not to load everything at once.
> 
> Of course that would be dumb. Always best to query the catalog so that it only contain what you need. It is a good idea to demonstrate the workflow and how to use the catalog. I can also include how to store cutout in their local directory of the whole catalog containing only the experiments they would be interested inn.
> 
> > Or we can try splitting the combined one by `institution_id`.
> 
> If we were to split it makes most sense to me to split according to `activity_id`.

It's up to you to decide. The only thing I care about is for documentation to be updated before the weekend.

**Comment by sarambl** [comment]
Hi @Ovewh , do you have an example of reading the CESM-PPE as well? I'm happy to make it if you just give me the location to use with intake. 
- [x] Reading CESM-PPE intake example

**Comment by mvdebolskiy** [comment]
@rlapere @juliaasp Can you add data description for the shared data you've uploaded?

**Comment by Ovewh** [comment]
@mvdebolskiy I made a mistake with the CESM json file. Could you remove the "ensamble" from groupby_attrs and change that aggregation control from join_existing to join_new. Like below

```
  "aggregation_control": {
    "variable_column_name": "variable",
    "groupby_attrs": [
      "experiment",
      "frequency"
    ],
    "aggregations": [
      {
        "type": "union",
        "attribute_name": "variable",
        "options": {}
      },
      {
        "type": "join_existing",
        "attribute_name": "time_range",
        "options": {
          "dim": "time",
          "coords": "minimal",
          "compat": "override"
        }
      },
      {
        "type": "join_new",
        "attribute_name": "ensemble",
        "options": {
          "dim": "ensamble",
          "coords": "minimal",
          "compat": "override"
        }
      }
    ]
  },
```

**Comment by mvdebolskiy** [comment]
Will do in a minute.

**Comment by rlapere** [comment]
@mvdebolskiy where do you suggest we put the data description?

**Comment by mvdebolskiy** [comment]
@rlapere in [./docs/data/local-data.rst ](https://github.com/MetOs-UiO/eScience2024/blob/master/docs/data/local-data.rst)
You can post it here if you struggle with restructured text format. I'll add it and make a PR. Also, look at the **Contribute** section on the web-page.

**Comment by mvdebolskiy** [comment]
@Ovewh try it now.

**Comment by Ovewh** [comment]
it this file that is the issue: `/mnt/craas1-ns9989k-geo4992/data/catalogs/cesm-ppe.json`

**Comment by mvdebolskiy** [comment]
> it this file that is the issue: `/mnt/craas1-ns9989k-geo4992/data/catalogs/cesm-ppe.json`

Yeah, I've replaced the aggregation control there.

**Comment by mvdebolskiy** [comment]
@rahulranjanaces can you add the description of the data you've added in [docs/data/local-data.rst](https://github.com/MetOs-UiO/eScience2024/blob/master/docs/data/local-data.rst) or just in the `docs/data/`? So, other people know what it is.
