### ISSUE TITLE
Move data pretty please? 

### ISSUE THREAD

**Issue by sarambl** [MetOs-UiO/eScience2024#55]
Hi @mvdebolskiy! Can you
'rsync /mnt/craas1-ns9989k-geo4992/dataporten-home/fc-3auid-3aeb54868a-2dc3bf-2d4cf2-2d9a1a-2d7ab42345078a/Data_raw/dap.ceda.ac.uk/badc/deposited2022/ /mnt/craas1-ns9989k-geo4992/data/data_group1/deposited2022/' 
please?

**Comment by mvdebolskiy** [comment]
@sarambl check the folder.

**Comment by sarambl** [comment]
🥳 🥳 🥳 🥳 🥳 🥳
