### ISSUE TITLE
Move data to data folder

### ISSUE THREAD

**Issue by sarambl** [MetOs-UiO/eScience2024#56]
Hi @mvdebolskiy ! Could you move:
/mnt/craas1-ns9989k-geo4992/dataporten-home/fc-3auid-3aeb54868a-2dc3bf-2d4cf2-2d9a1a-2d7ab42345078a/Data_raw/MERRA-2

to 

/mnt/craas1-ns9989k-geo4992/data/data_group1/

?

Thanks a lot :D

**Comment by mvdebolskiy** [comment]
Done. You can delete it from your home.

**Comment by sarambl** [comment]
Thanks!
